In [1]:
import pandas as pd
import numpy as np

basket = pd.read_csv("basket_details.csv")
customers = pd.read_csv("customer_details.csv")

print("Datos cargados correctamente")

Datos cargados correctamente

In [2]:
#ver las primeras 5 filas de la tabla basket
basket.head()

   customer_id  product_id basket_date  basket_count
0     42366585    41475073  2019-06-19             2
1     35956841    43279538  2019-06-19             2
2     26139578    31715598  2019-06-19             3
3      3262253    47880260  2019-06-19             2
4     20056678    44747002  2019-06-19             2

In [3]:
#ver las primeras 5 filas de la tabla customers
customers.head()

   customer_id   sex  customer_age  tenure
0      9798859  Male          44.0      93
1     11413563  Male          36.0      65
2       818195  Male          35.0     129
3     12049009  Male          33.0      58
4     10083045  Male          42.0      88

In [4]:
#tipo de dato y valores nulos de la tabla basket
basket.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   15000 non-null  int64
 1   product_id    15000 non-null  int64
 2   basket_date   15000 non-null  str
 3   basket_count  15000 non-null  int64
dtypes: int64(3), str(1)
memory usage: 468.9 KB

In [5]:
#tipo de datos y valores nulos de la tabla customers
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   20000 non-null  int64
 1   sex           20000 non-null  str
 2   customer_age  20000 non-null  float64
 3   tenure        20000 non-null  int64
dtypes: float64(1), int64(2), str(1)
memory usage: 625.1 KB

In [6]:
#contar filas duplicadas en cada tabla 
print ("Duplicados en basket:", basket.duplicated().sum())
print ("Duplicados en customers:", customers.duplicated().sum())

Duplicados en basket: 0
Duplicados en customers: 0

In [7]:
#convertir la columna de texto a tipo fecha (datetime)
basket["basket_date"] = pd.to_datetime(basket["basket_date"])

#verificar que el cambio funciono
basket.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   15000 non-null  int64
 1   product_id    15000 non-null  int64
 2   basket_date   15000 non-null  datetime64[us]
 3   basket_count  15000 non-null  int64
dtypes: datetime64[us](1), int64(3)
memory usage: 468.9 KB

In [8]:
#convertir la edad de decimal (float) a entero (int)
customers["customer_age"] = customers["customer_age"].astype(int)

#verificar que el cambio funciono
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   20000 non-null  int64
 1   sex           20000 non-null  str
 2   customer_age  20000 non-null  int64
 3   tenure        20000 non-null  int64
dtypes: int64(3), str(1)
memory usage: 625.1 KB

In [9]:
#resumen estadistico de las columnas numericas
print ("== customers ==")
print (customers[["customer_age", "tenure"]].describe())

print ("\n=== basket ===")
print (basket["basket_count"].describe())

== customers ==
       customer_age        tenure
count  20000.000000  20000.000000
mean     262.222550     44.396800
std      604.321589     31.998376
min      -34.000000      4.000000
25%       29.000000     21.000000
50%       38.000000     35.000000
75%      123.000000     60.000000
max     2022.000000    133.000000

=== basket ===
count    15000.000000
mean         2.153733
std          0.517929
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max         10.000000
Name: basket_count, dtype: float64

In [10]:
#contar cuantos clientes tienen edades fera del rango logico (18 a 90)
fuera_de_rango = customers[(customers ["customer_age"] < 18) | (customers["customer_age"] > 90)]

print ("clientes con edad imposible:", len(fuera_de_rango))
print ("total de cliente:", len(customers))
print ("porcentaje:", round(len(fuera_de_rango) / len(customers) * 100,2), "%")

clientes con edad imposible: 7455
total de cliente: 20000
porcentaje: 37.28 %

In [11]:
#calcular la mediana solo conas edades validas entre 18 y 90
edades_validas = customers[(customers["customer_age"] >= 18) & (customers["customer_age"]>=90)]
mediana_edad = edades_validas["customer_age"].median()

print ("mediana de edad (Solo validas):", mediana_edad)
print ("clientes validos:", len(edades_validas))

mediana de edad (Solo validas): 123.0
clientes validos: 6710

In [12]:
#1. confirmar el tipo de dato actual
print("tipo de dato:", customers["customer_age"].dtype)

#2. ver los valores unicos ordenados los 10 mas bajos y 10 mas altos
print("\n10 edades mas bajas:", sorted(customers["customer_age"].unique())[:10])
print("10 edades mas altas:", sorted(customers["customer_age"].unique())[-10:])

#3. volver a contar, paso a paso
menores_18 = (customers["customer_age"] < 18).sum()
mayores_90 = (customers["customer_age"] > 90).sum()
en_rango = ((customers["customer_age"] >= 18) & (customers["customer_age"] <= 90)).sum()

print("\nMenores de 18:", menores_18)
print("Mayores de 90:", mayores_90)
print("En rango (18 - 90):", en_rango)
print("Suma total:", menores_18 + mayores_90 + en_rango)

tipo de dato: int64

10 edades mas bajas: [np.int64(-34), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(12), np.int64(13), np.int64(15), np.int64(16), np.int64(17)]
10 edades mas altas: [np.int64(120), np.int64(121), np.int64(122), np.int64(123), np.int64(124), np.int64(127), np.int64(130), np.int64(139), np.int64(149), np.int64(2022)]

Menores de 18: 745
Mayores de 90: 6710
En rango (18 - 90): 12545
Suma total: 20000

In [13]:
#mediana solo con la edades validas 18 a 90
edades_validas = customers[(customers["customer_age"] >= 18) & (customers["customer_age"] <= 90)]
mediana_edad = edades_validas["customer_age"].median()

print("mediana de edad (solo validas):", mediana_edad)
print("clientes validos:", len(edades_validas))

mediana de edad (solo validas): 32.0
clientes validos: 12545

In [14]:
#reemplazar edades fuera de rango 18 a 90 por la mediana 32
condicion_imposible = (customers["customer_age"] < 18) | (customers["customer_age"] > 90)
customers.loc[condicion_imposible, "customer_age"] = mediana_edad

#convertir de nuevo a entero (por si la mediana quedo como decimal)
customers["customer_age"] = customers["customer_age"].astype(int)

#verificar que ahora todo este en rango
print(customers["customer_age"].describe())

count    20000.000000
mean        33.115350
std          6.989613
min         18.000000
25%         30.000000
50%         32.000000
75%         34.000000
max         86.000000
Name: customer_age, dtype: float64

In [15]:
#contar cuantos productos unicos existen
print("productos unicos:", basket["product_id"].nunique())

productos unicos: 13161

In [16]:
#fijamos una semilla para que los resultados sean siempre iguales (reproducibles)
np.random.seed(42)

#1. lista de productos unicos
productos = basket["product_id"].unique()

#2. categorias y sus rangos de precios (USD)
categorias = {
    "Electronica": (50, 1500),
    "Ropa": (10, 200),
    "Hogar": (15, 500),
    "Belleza": (5, 120),
    "Deportes": (20, 400),
    "Libros": (5, 60)
}

nombres_cat = list(categorias.keys())

#3. asignar una categoria al azar a cada producto
cat_asignada = np.random.choice(nombres_cat, size=len(productos))

#4. generar un precio segun el rango de su categoria
precios = []
for cat in cat_asignada:
    minimo, maximo = categorias[cat]
    precio = round(np.random.uniform(minimo, maximo), 2)
    precios.append(precio)

#5. construir la tabla del catalogo
catalogo = pd.DataFrame({
    "product_id": productos,
    "category": cat_asignada,
    "price": precios
})

#6 guardar en un archivo CSV
catalogo.to_csv("product_catalog.csv", index=False)

#ver las primeras filas
print("catalogo creado con", len(catalogo), "productos")
catalogo.head()

catalogo creado con 13161 productos

   product_id  category   price
0    41475073   Belleza   94.39
1    43279538  Deportes  336.20
2    31715598     Hogar  190.21
3    47880260  Deportes  101.08
4    44747002  Deportes  166.32

In [17]:
#unir basket con el catalogo usando producto_id como llave
ventas = basket.merge(catalogo, on="product_id", how="left")

#ver el resultado
print("Filas en ventas:", len(ventas))
ventas.head()

Filas en ventas: 15000

   customer_id  product_id basket_date  basket_count  category   price
0     42366585    41475073  2019-06-19             2   Belleza   94.39
1     35956841    43279538  2019-06-19             2  Deportes  336.20
2     26139578    31715598  2019-06-19             3     Hogar  190.21
3      3262253    47880260  2019-06-19             2  Deportes  101.08
4     20056678    44747002  2019-06-19             2  Deportes  166.32

In [18]:
#crear columna de ingreso: precio x cantidad comprada
ventas["revenue"] = ventas["price"] * ventas["basket_count"]

#ver el resultado
ventas.head()

,customer_id,product_id,basket_date,basket_count,category,price,revenue
0,42366585,41475073,2019-06-19,2,Belleza,94.39,188.78
1,35956841,43279538,2019-06-19,2,Deportes,336.20,672.40
2,26139578,31715598,2019-06-19,3,Hogar,190.21,570.63
3,3262253,47880260,2019-06-19,2,Deportes,101.08,202.16
4,20056678,44747002,2019-06-19,2,Deportes,166.32,332.64

In [19]:
import sqlite3

#crear conexion a una base de datos SQLITE
conn = sqlite3.connect("ecommerce.db")

#subir muestras tablas a la base de datos
ventas.to_sql("ventas", conn, if_exists="replace", index=False)
customers.to_sql("customers", conn, if_exists="replace", index=False)

print("Base de datos lista. Ya podemos usar SQL")

Base de datos lista. Ya podemos usar SQL

In [20]:
#funcion para ejecutar SQL y mostrar el resultado como tabla
def sql(query):
    return pd.read_sql_query(query, conn)

In [21]:
sql(""" 
    SELECT COUNT(*) AS TOTAL_ventas
    FROM ventas
""")

   TOTAL_ventas
0         15000

In [22]:
sql(""" 
    SELECT ROUND(SUM(revenue), 2) AS ingreso_total
    FROM ventas
""")

   ingreso_total
0     7766640.17

In [23]:
sql(""" 
    SELECT ROUND(AVG(price), 2) AS precio_promedio
    FROM ventas
""")

   precio_promedio
0           240.27

In [24]:
sql(""" 
    SELECT product_id,
           SUM(basket_count) AS unidades_vendidas
    FROM ventas
    GROUP BY product_id
    ORDER BY unidades_vendidas DESC
    LIMIT 10
""")

   product_id  unidades_vendidas
0    43524799                 69
1    31516269                 59
2    39833031                 50
3    46130148                 36
4    34913531                 28
5    40276011                 27
6     3735903                 27
7    42033035                 23
8     6411072                 23
9    39050110                 22

In [25]:
sql(""" 
    SELECT category,
            ROUND(SUM(revenue),2) AS ingresos
    FROM ventas
    GROUP BY category
    ORDER BY ingresos DESC
""")

      category    ingresos
0  Electronica  4189651.69
1        Hogar  1346601.69
2     Deportes  1156045.69
3         Ropa   561154.20
4      Belleza   339565.76
5       Libros   173621.14

In [26]:
sql(""" 
    SELECT customer_id,
            ROUND(SUM(revenue), 2) AS total_facturado
    FROM ventas
    GROUP BY customer_id
    ORDER BY total_facturado DESC
    LIMIT 10
""")

   customer_id  total_facturado
0     15277082         10436.00
1     29582629          9535.40
2     29142937          8712.96
3     42095751          8598.90
4     19825480          7442.90
5     29145357          7263.07
6     20098151          6531.16
7      2719296          6087.84
8     11732494          5908.98
9      1333596          5660.85

In [27]:
sql(""" 
    SELECT customer_id,
            COUNT(*) AS num_compras
    FROM ventas
    GROUP BY customer_id
    HAVING COUNT(*) > 5 
    ORDER BY num_compras DESC
""")

   customer_id  num_compras
0     11082470            8
1      8276934            8
2     18617678            6

In [28]:
sql(""" 
    WITH ranking AS (
        SELECT category,
                product_id,
                SUM(basket_count) AS unidades,
                RANK() OVER (PARTITION BY category ORDER BY SUM(basket_count) DESC) AS puesto
        FROM ventas
        GROUP BY category, product_id
    )
    SELECT category, product_id, unidades
    FROM ranking
    WHERE puesto = 1
""")

      category  product_id  unidades
0      Belleza    43524799        69
1     Deportes    31516269        59
2  Electronica     6411072        23
3        Hogar     3735903        27
4       Libros    34913531        28
5         Ropa    39050110        22

In [29]:
sql(""" 
    SELECT strftime('%Y-%m', basket_date) AS mes,
            ROUND(SUM(revenue), 2) AS ingresos
    FROM ventas
    GROUP BY mes
    ORDER BY mes
""")

       mes    ingresos
0  2019-05  4611310.45
1  2019-06  3155329.72

In [30]:
sql(""" 
   WITH ventas_mes AS (
        SELECT strftime('%Y-%m', basket_date) AS mes,
               SUM(revenue) AS ingresos
        FROM ventas
        GROUP BY mes
    )
    SELECT mes,
           ROUND(ingresos, 2) AS ingresos,
           ROUND(LAG(ingresos) OVER (ORDER BY mes), 2) AS mes_anterior,
           ROUND(ingresos - LAG(ingresos) OVER (ORDER BY mes), 2) AS diferencia,
           ROUND((ingresos - LAG(ingresos) OVER (ORDER BY mes)) 
                 / LAG(ingresos) OVER (ORDER BY mes) * 100, 2) AS crecimiento_pct
    FROM ventas_mes
    ORDER BY mes
""")

       mes    ingresos  mes_anterior  diferencia  crecimiento_pct
0  2019-05  4611310.45           NaN         NaN              NaN
1  2019-06  3155329.72    4611310.45 -1455980.73           -31.57

In [31]:
sql(""" 
    SELECT category,
            ROUND(SUM(revenue), 2) AS ingresos,
            ROUND(SUM(revenue) * 100.0 / (SELECT SUM(revenue) FROM ventas), 2) AS porcentaje
    FROM ventas
    GROUP BY category
    ORDER BY porcentaje DESC
""")

      category    ingresos  porcentaje
0  Electronica  4189651.69       53.94
1        Hogar  1346601.69       17.34
2     Deportes  1156045.69       14.88
3         Ropa   561154.20        7.23
4      Belleza   339565.76        4.37
5       Libros   173621.14        2.24

In [32]:
sql(""" 
    WITH ranking AS (
        SELECT category,
                product_id,
                ROUND(SUM(revenue), 2) AS ingresos,
                RANK() OVER (PARTITION BY category ORDER BY SUM(revenue) DESC) AS puesto
        FROM ventas
        GROUP BY category, product_id
    )
    SELECT category, product_id, ingresos, puesto
    FROM ranking
    WHERE puesto <= 3 
    ORDER BY category, puesto
""")

       category  product_id  ingresos  puesto
0       Belleza    39833031   5516.50       1
1       Belleza    43524799   3176.76       2
2       Belleza    40276011   2014.47       3
3      Deportes     3675590   7718.60       1
4      Deportes    31516269   7531.94       2
5      Deportes      579438   5542.46       3
6   Electronica    31843261  32748.76       1
7   Electronica     1008436  15018.78       2
8   Electronica    40276058  14467.84       3
9         Hogar    35134963  10312.47       1
10        Hogar    40275998   8759.88       2
11        Hogar     3735903   8588.70       3
12       Libros    34913531   1611.96       1
13       Libros    42033035   1336.99       2
14       Libros    33906448    728.10       3
15         Ropa    39050110   4385.26       1
16         Ropa    34764196   2593.64       2
17         Ropa    33906453   2315.30       3

In [33]:
sql(""" 
    WITH ventas_mes AS (
        SELECT strftime('%Y-m%', basket_date) AS mes,
                SUM(revenue) AS ingresos
        FROM ventas
        GROUP BY mes
    )
    SELECT mes,
            ROUND(ingresos, 2) AS ventas_mes_actual,
            ROUND(LAG(ingresos) OVER (ORDER BY mes), 2) AS ventas_mes_anterior
    FROM ventas_mes
    ORDER BY MES
""")

    mes  ventas_mes_actual ventas_mes_anterior
0  None         7766640.17                None

In [34]:
sql("""
    SELECT basket_date
    FROM ventas
    LIMIT 3
""")

           basket_date
0  2019-06-19 00:00:00
1  2019-06-19 00:00:00
2  2019-06-19 00:00:00

In [35]:
sql("""
    WITH ventas_mes AS (
        SELECT substr(basket_date, 1, 7) AS mes,
                SUM(revenue) AS ingresos
        FROM ventas
        GROUP BY mes
    )
    SELECT mes,
            ROUND(ingresos, 2) AS ventas_mes_actual,
            ROUND(LAG(ingresos) OVER (ORDER BY mes), 2) AS ventas_mes_anterior
    FROM ventas_mes
    ORDER BY mes
""")

       mes  ventas_mes_actual  ventas_mes_anterior
0  2019-05         4611310.45                  NaN
1  2019-06         3155329.72           4611310.45

In [36]:
sql(""" 
    WITH ventas_mes AS (
        SELECT substr(basket_date, 1, 7) AS mes,
                SUM(revenue) AS ingresos
        FROM ventas
        GROUP BY mes
    )
    SELECT mes,
            ROUND(ingresos, 2) AS ingresos_mes,
            ROUND(SUM(ingresos) OVER (ORDER BY mes), 2) AS acumulado
    FROM ventas_mes
    ORDER BY mes    
""")

       mes  ingresos_mes   acumulado
0  2019-05    4611310.45  4611310.45
1  2019-06    3155329.72  7766640.17

In [37]:
sql("""
    WITH gasto_cliente AS (
        SELECT customer_id,
                SUM(revenue) AS total_gastado
        FROM ventas
        GROUP BY customer_id
    )
    SELECT customer_id,
            ROUND(total_gastado, 2) AS total_gastado,
            CASE
                WHEN total_gastado > 3000 THEN 'VIP'
                WHEN total_gastado >= 1000 THEN 'Frecuente'
                ELSE 'Ocacional'
            END AS tipo_cliente
    FROM gasto_cliente
    ORDER BY total_gastado DESC
    LIMIT 15
""")

    customer_id  total_gastado tipo_cliente
0      15277082       10436.00          VIP
1      29582629        9535.40          VIP
2      29142937        8712.96          VIP
3      42095751        8598.90          VIP
4      19825480        7442.90          VIP
5      29145357        7263.07          VIP
6      20098151        6531.16          VIP
7       2719296        6087.84          VIP
8      11732494        5908.98          VIP
9       1333596        5660.85          VIP
10      7564832        5584.66          VIP
11     11680103        5526.86          VIP
12     30264141        5512.80          VIP
13     13565747        5485.16          VIP
14     40381125        5480.17          VIP

In [38]:
sql("""
    WITH gasto_cliente AS (
        SELECT customer_id,
                SUM(revenue) AS total_gastado
        FROM ventas
        GROUP BY customer_id
    )
    SELECT CASE
                WHEN total_gastado > 3000 THEN 'VIP'
                WHEN total_gastado >= 1000 THEN 'Frecuente'
                ELSE 'Ocasional'
            END AS tipo_cliente,
            COUNT(*) AS cantidad_clientes
    FROM gasto_cliente
    GROUP BY tipo_cliente
    ORDER BY cantidad_clientes DESC
""")

  tipo_cliente  cantidad_clientes
0    Ocasional              11825
1    Frecuente               1886
2          VIP                160

In [39]:
sql("""
    WITH gasto_cliente AS (
        SELECT customer_id,
                SUM(revenue) AS total_gastado
        FROM ventas
        GROUP BY customer_id
    )
    SELECT customer_id,
            ROUND(total_gastado, 2) AS total_gastado
    FROM gasto_cliente
    WHERE total_gastado > (SELECT AVG(total_gastado) FROM gasto_cliente)
    ORDER BY total_gastado DESC
    LIMIT 15
""")

    customer_id  total_gastado
0      15277082       10436.00
1      29582629        9535.40
2      29142937        8712.96
3      42095751        8598.90
4      19825480        7442.90
5      29145357        7263.07
6      20098151        6531.16
7       2719296        6087.84
8      11732494        5908.98
9       1333596        5660.85
10      7564832        5584.66
11     11680103        5526.86
12     30264141        5512.80
13     13565747        5485.16
14     40381125        5480.17

In [40]:
#explorar la tabla de ventas listas para power BI
ventas.to_csv("ventas_powerbi.csv", index=False)

#exporta tambien la tabla de clientes (la usaremos para segmentar)
customers.to_csv("customers_powerbi.csv", index=False)


print("Archivos exportados correctamente")
print("- ventas_powerbi.csv:", ventas.shape)
print("- customers_powerbi.csv", customers.shape)

Archivos exportados correctamente
- ventas_powerbi.csv: (15000, 7)
- customers_powerbi.csv (20000, 4)

In [41]:
#¿cuantos customer_id de ventas existen tambien en customers?
ids_ventas = set(ventas["customer_id"].unique())
ids_customers = set(customers["customer_id"].unique())

print("clientes unicos en ventas:", len(ids_ventas))
print("clientes unicos en customers:", len(ids_customers))
print("coinciden en ambas tablas:", len(ids_ventas & ids_customers))
print("en ventas pero NO en customers:", len(ids_ventas - ids_customers))

clientes unicos en ventas: 13871
clientes unicos en customers: 20000
coinciden en ambas tablas: 64
en ventas pero NO en customers: 13807

In [42]:
#gasto total por cliente (desde VENTAS, igual que mi sql)
seg = ventas.groupby("customer_id")["revenue"].sum().reset_index()
seg.columns = ["customer_id", "gasto_total"]

#clasificar (mismo criterio que la pregunta 14 que respondi)
def clasificar(g):
    if g > 3000:
        return "VIP"
    elif g >= 1000:
        return "Frecuente"
    else:
        return "Ocacional"
seg["tipo_cliente"] = seg ["gasto_total"].apply(clasificar)

#exportar listo para power bi
seg.to_csv("segmentacion_cliente1.csv", index=False)

print("Archivo creado: segmentacio_clientes.csv")
print(seg["tipo_cliente"].value_counts())
print("\nTotal cliente:", len (seg))

Archivo creado: segmentacio_clientes.csv
tipo_cliente
Ocacional    11825
Frecuente     1886
VIP            160
Name: count, dtype: int64

Total cliente: 13871